import { expect, test, type Page } from '@playwright/test'

async function puncture(page: Page, x: number, y: number) {
  await page.locator('#hoop-shell').scrollIntoViewIfNeeded()
  const b = (await page.locator('#embroidery').boundingBox())!
  await page.mouse.click(b.x + b.width * x, b.y + b.height * y)
}
const artwork = (page: Page) => page.evaluate(() => JSON.parse(localStorage.getItem('deesewsew-piece-v1')!))
test('Ctrl click commits once on release and cancels drag, Escape, capture loss and blur',async({page})=>{
  await page.goto('/DeeSewSew/');await page.locator('#motion-toggle').click()
  await puncture(page,.3,.4);await puncture(page,.4,.4)
  const before=await artwork(page),shell=page.locator('#hoop-shell')
  const b=(await page.locator('#embroidery').boundingBox())!,x=b.x+b.width*.5,y=b.y+b.height*.5
  for(const cancellation of ['drag','Escape','pointercancel','lostpointercapture','blur']){
    await page.mouse.move(x,y);await page.keyboard.down('Control');await page.mouse.down()
    expect(await artwork(page)).toEqual(before)
    if(cancellation==='drag')await page.mouse.move(x+20,y)
    else if(cancellation==='Escape')await page.keyboard.press('Escape')
    else if(cancellation==='blur')await page.evaluate(()=>window.dispatchEvent(new Event('blur')))
    else await shell.dispatchEvent(cancellation,{pointerId:1,pointerType:'mouse',isPrimary:true})
    await page.mouse.up();await page.keyboard.up('Control')
    expect(await artwork(page)).toEqual(before)
  }
  await page.mouse.move(x,y);await page.keyboard.down('Control');await page.mouse.down()
  expect(await artwork(page)).toEqual(before)
  const suppressed=await shell.evaluate(el=>!el.dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,cancelable:true,ctrlKey:true})))
  expect(suppressed).toBe(true)
  await page.mouse.move(x+2,y+2);await page.mouse.up();await page.keyboard.up('Control')
  const cut=await artwork(page)
  expect(cut.activeRunId).toBeNull();expect(cut.punctures).toEqual(before.punctures)
  expect(cut.nextOrder).toBe(before.nextOrder+1)
  expect(await page.locator('.masthead').evaluate(el=>el.dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,cancelable:true,button:2})))).toBe(true)
  await page.locator('#undo').click();expect((await artwork(page)).activeRunId).toBe(before.activeRunId)
  await page.locator('#redo').click();expect(await artwork(page)).toEqual(cut)
})
test('end/new same-color run, boundary undo/redo and reload preserve disconnected geometry', async ({ page }, info) => {
  await page.addInitScript(() => localStorage.setItem('deesewsew-locale-v1', 'en'))
  await page.goto('/DeeSewSew/'); await page.locator('#motion-toggle').click()
  await expect(page.locator('#end-thread')).toBeDisabled()
  await puncture(page,.3,.4); await puncture(page,.4,.4)
  const first = await artwork(page)
  await page.locator('#end-thread').click()
  const ended = await artwork(page)
  expect(ended.needle).toEqual(first.needle); expect(ended.activeRunId).toBeNull()
  await expect(page.locator('#end-thread')).toBeDisabled()
  await page.locator('#undo').click(); expect((await artwork(page)).activeRunId).toBe(first.activeRunId)
  await page.locator('#redo').click(); expect(await artwork(page)).toEqual(ended)
  await page.reload()
  await expect(page.locator('#end-thread')).toBeDisabled()
  await puncture(page,.6,.6)
  expect((await artwork(page)).segments).toEqual(first.segments)
  await puncture(page,.7,.6)
  const complete = await artwork(page)
  expect(complete.schemaVersion).toBe(4); expect(complete.runs).toHaveLength(2)
  expect(complete.segments).toHaveLength(2)
  expect(complete.runs[0].color).toBe(complete.runs[1].color)
  expect(complete.runs[0].id).not.toBe(complete.runs[1].id)
  await page.locator('#undo').click(); await page.locator('#undo').click(); await page.locator('#undo').click()
  expect((await artwork(page)).activeRunId).toBe(first.activeRunId)
  for(let i=0;i<3;i++)await page.locator('#redo').click()
  expect(await artwork(page)).toEqual(complete)
  await page.reload(); expect(await artwork(page)).toEqual(complete)
  await page.mouse.move(0,0)
  await page.screenshot({path:info.outputPath('thread-runs-front.png'),fullPage:true})
  await page.locator('#view-back').click()
  await page.screenshot({path:info.outputPath('thread-runs-back.png'),fullPage:true})
  await info.attach('same-color-two-runs.json',{body:JSON.stringify(complete,null,2),contentType:'application/json'})
})

test('different color ends old physical run; zh/en control and export/import remain truthful', async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('deesewsew-locale-v1', 'en'))
  await page.goto('/DeeSewSew/');await page.locator('#motion-toggle').click()
  await puncture(page,.3,.4);await puncture(page,.4,.4)
  const before=await artwork(page)
  await page.locator('#palette .swatch').nth(1).click()
  const ended=await artwork(page)
  expect(ended.activeRunId).toBeNull();expect(ended.segments).toEqual(before.segments)
  await puncture(page,.6,.6);await puncture(page,.7,.6)
  const finished=await artwork(page)
  expect(finished.runs).toHaveLength(2)
  expect(finished.runs[1].color).not.toBe(finished.runs[0].color)
  expect(finished.segments).toHaveLength(2)
  await page.getByRole('button',{name:'中文',exact:true}).click()
  await expect(page.locator('#end-thread')).toHaveText('剪线')
  await page.getByRole('button',{name:'English',exact:true}).click()
  const download=page.waitForEvent('download');await page.locator('#export-artwork').click()
  const file=await download;expect(await file.failure()).toBeNull()
  await page.reload();expect(await artwork(page)).toEqual(finished)
  const imported=JSON.stringify(finished)
  page.once('dialog',d=>d.accept())
  await page.locator('#artwork-file').setInputFiles({name:'multi-run.json',mimeType:'application/json',buffer:Buffer.from(imported)})
  await expect(page.locator('#status-title')).toHaveText('Artwork imported')
  expect(await artwork(page)).toEqual(finished)
})
